services:
  app:
    image: eu-vat-validator
    build: .
    volumes:
      - .:/var/www/app
      - ./www.conf:/usr/local/etc/php/conf.d/www.conf
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
